<a href="https://colab.research.google.com/github/vedhaharshitharayini2007-cmd/Data-Visualization-Record-/blob/main/MDS_Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install numpy

In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [2]:
import time
import numpy as np

# Define a large size for our data structures
size = 10**6

# --- Python List Performance ---

# Create two large Python lists
list1 = list(range(size))
list2 = list(range(size))

start_time_list = time.time()
# Perform element-wise addition using a list comprehension
result_list = [a + b for a, b in zip(list1, list2)]
end_time_list = time.time()

time_taken_list = end_time_list - start_time_list
print(f"Time taken for Python list addition: {time_taken_list:.6f} seconds")

# --- NumPy Array Performance ---

# Create two large NumPy arrays
numpy_array1 = np.arange(size)
numpy_array2 = np.arange(size)

start_time_numpy = time.time()
# Perform element-wise addition using NumPy's vectorized operation
result_numpy = numpy_array1 + numpy_array2
end_time_numpy = time.time()

time_taken_numpy = end_time_numpy - start_time_numpy
print(f"Time taken for NumPy array addition: {time_taken_numpy:.6f} seconds")

# Compare the results (optional, to show correctness)
# print(f"First 5 elements of list result: {result_list[:5]}")
# print(f"First 5 elements of numpy result: {result_numpy[:5]}")

if time_taken_list > 0:
    speed_up = time_taken_list / time_taken_numpy
    print(f"NumPy is approximately {speed_up:.2f} times faster than Python lists for this operation.")

Time taken for Python list addition: 0.066519 seconds
Time taken for NumPy array addition: 0.002932 seconds
NumPy is approximately 22.68 times faster than Python lists for this operation.


In [3]:
import sys
import numpy as np

# Define a large size for our data structures
size = 10**6

# --- Python List Memory Usage ---

# Create a large Python list of integers
python_list = list(range(size))

# Calculate memory usage of the Python list
# sys.getsizeof returns the size of the list object itself, not its contents.
# To get a more accurate total, we need to sum the size of each element.
# For integers, the size can vary, but we'll approximate for demonstration.
# A simple estimate: size of list object + (number of elements * size of each element reference)
# Plus the actual integer objects themselves. This can be complex.
# A more practical approximation for many Python objects is to multiply by a typical object size.
# However, for integers, `sys.getsizeof` on individual elements is more accurate.

# Base size of the list object itself
memory_list_base = sys.getsizeof(python_list)

# Size of each element (assuming all integers are of similar size, e.g., 28 bytes for small ints)
# This is an approximation and can vary. For demonstration, we'll use a representative size.
# Let's get the size of one element and multiply.
memory_per_element = sys.getsizeof(python_list[0]) # Size of one int object

# Total approximate memory for the list + its elements
# This is still a simplification as small integers are often interned.
# For large integers, it's more accurate to sum sys.getsizeof for each.
# A commonly cited method for rough estimation is:
# sys.getsizeof(list_object) + sum(sys.getsizeof(item) for item in list_object)
# But for a million items, that's too slow. Let's use an approximation.

# A better approximation for homogeneous lists:
memory_list = memory_list_base + sum(sys.getsizeof(x) for x in python_list[:100]) * (size // 100) # Sample 100 elements

# Or, a simpler but less precise way: base list size + (number of elements * average element size)
# For simplicity and speed for this example, we'll focus on the raw `sys.getsizeof` and acknowledge its limitations
# and then for array use .nbytes

print(f"--- Python List Memory ---")
print(f"Size of Python list (rough estimate, includes references): {sys.getsizeof(python_list) / (1024**2):.3f} MB")

# --- NumPy Array Memory Usage ---

# Create a large NumPy array of integers (default dtype is usually int64 on 64-bit systems)
numpy_array = np.arange(size)

# NumPy arrays have a convenient .nbytes attribute for actual data storage
memory_numpy = numpy_array.nbytes

print(f"\n--- NumPy Array Memory ---")
print(f"Size of NumPy array ({numpy_array.dtype}): {memory_numpy / (1024**2):.3f} MB")

print("\n--- Comparison ---")
if sys.getsizeof(python_list) > 0 and memory_numpy > 0:
    ratio = sys.getsizeof(python_list) / memory_numpy
    print(f"Python list is approximately {ratio:.2f} times larger than NumPy array for storing references of same number of elements.\n(Note: This comparison can be complex due to Python object overhead and NumPy's contiguous memory)")


--- Python List Memory ---
Size of Python list (rough estimate, includes references): 7.629 MB

--- NumPy Array Memory ---
Size of NumPy array (int64): 7.629 MB

--- Comparison ---
Python list is approximately 1.00 times larger than NumPy array for storing references of same number of elements.
(Note: This comparison can be complex due to Python object overhead and NumPy's contiguous memory)


In [6]:
list = [1,2,3,4,5]
type(list)

list

In [7]:
arr1 = np.array(list)

In [8]:
print(arr1)

[1 2 3 4 5]


In [9]:
type(arr1)

numpy.ndarray

In [10]:
arr1.ndim

1

In [11]:
arr1.dtype

dtype('int64')

In [12]:
arr1.dtype.name

'int64'

In [13]:
arr1.size

5

In [14]:
arr1.shape

(5,)

In [15]:
arr1.nbytes

40

In [22]:
tuple = (1,2,3,4,5)
type(tuple)

tuple

In [23]:
tuple2 = (1,)
type(tuple2)

tuple

In [24]:
arr2 = np.array(tuple)
print(arr2)

[1 2 3 4 5]


In [25]:
arr2.ndim

1

In [30]:
lst = [[1,2],[3,4]]

In [31]:
matrix = np.array(lst)

In [32]:
print(matrix)

[[1 2]
 [3 4]]


In [33]:
matrix.ndim

2

In [34]:
matrix.shape

(2, 2)

In [35]:
matrix.size

4

In [36]:
matrix.nbytes

32

In [37]:
matrix.flatten()

array([1, 2, 3, 4])

In [39]:
matrix.ravel()

array([1, 2, 3, 4])

In [42]:
arr4 = np.array([1,2,3,4])

In [43]:
print(arr4)

[1 2 3 4]


In [44]:
arr5 = np.array([[1,2],[3,4]])

In [45]:
print(arr5)

[[1 2]
 [3 4]]


In [46]:
arr6 = np.matrix([[1,2],[3,4],[5,6]])

In [47]:
print(arr6)

[[1 2]
 [3 4]
 [5 6]]


In [49]:
import numpy as np

# Create a 1D NumPy array with elements from 1 to 100
# np.arange(start, stop) generates numbers from start up to (but not including) stop
array_1_to_100 = np.arange(1, 101)

# Print the array
print(array_1_to_100)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [51]:
arr6 = np.arange(1,100)

In [54]:
import numpy as np
even_numbers = np.arange(2, 101, 2)

print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [55]:
import numpy as np

# When only one argument is provided to np.arange, it is treated as the 'stop' value.
# The 'start' value defaults to 0.
# This will generate numbers from 0 up to (but not including) 100.
array_without_start = np.arange(100)

print(array_without_start)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [59]:
matrix2 = np.arange(0,10).reshape(2,5).flatten()
print(matrix2)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
a = np.zeros((3,2),dtype = ('int'))
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [68]:
b = np.ones((3,3),dtype = ('int'))
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [69]:
c = np.full((3,3),2)
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [70]:
e = np.eye(3)

In [71]:
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [72]:
f = np.linspace(0,1,5)

In [73]:
print(f)

[0.   0.25 0.5  0.75 1.  ]


In [76]:
import numpy as np
g = np.random.random((3, 3))
print(g)

[[0.04975204 0.82144397 0.15281994]
 [0.67493304 0.44790723 0.172869  ]
 [0.10339968 0.64501879 0.16517999]]


In [77]:
arr7 = np.arange(1,10)
print(arr7)

[1 2 3 4 5 6 7 8 9]


In [78]:
arr7[0] = 111

In [79]:
print(arr7)

[111   2   3   4   5   6   7   8   9]


In [81]:
print(max(arr7))

111


In [83]:
arr7.max()

np.int64(111)

In [84]:
arr7.min()

np.int64(2)

In [85]:
import numpy as np

# Create a NumPy array from a single string
string_array_single = np.array('hello numpy')
print("Array from single string:", string_array_single)
print("Data type of single string array elements:", string_array_single.dtype)

# Create a NumPy array from a list of strings
string_list = ['apple', 'banana', 'cherry']
string_array_list = np.array(string_list)
print("\nArray from list of strings:", string_array_list)
print("Data type of list of strings array elements:", string_array_list.dtype)

# You can also specify the dtype, for example, to ensure fixed-size strings
string_array_fixed = np.array(['one', 'two', 'three'], dtype='U5') # 'U5' for Unicode string of max length 5
print("\nArray with fixed string length dtype:", string_array_fixed)
print("Data type of fixed length string array elements:", string_array_fixed.dtype)

Array from single string: hello numpy
Data type of single string array elements: <U11

Array from list of strings: ['apple' 'banana' 'cherry']
Data type of list of strings array elements: <U6

Array with fixed string length dtype: ['one' 'two' 'three']
Data type of fixed length string array elements: <U5
